* Thumbs
** The Sort
- Narrator: We are outside the Brute Force Sorting Hall
- [Cut to] Steps of Brute Force Sorting Hall, interior columns visible. Bubba stands outside on the steps
- [Cut to interior in front of door at back of hall, Bubba has moved in front of the door].
- Bubba: Want to see how Bubba sorts?
- Bubba: Right in here's where we work.
- [Bubba stands next to Manta Ray]
- Bubba: This is Ray, he's a ray. Say hey, Ray.
- Ray: Hey.
- [beat]
- Ray: Oh. Hey, Ray.
- [Bubba Laughs]
- Bubba: This guy. Crack me up.
- Bubba: Anyway.
- Bubba: The stuff we sort (in this case rocks) are kept in what we call a ray.
- Ray: Array.
- Bubba: A ray.
- Ray: Array.
- Bubba [aside]: Humor him, this is his place.
- Bubba: The rocks are in this array.
- Bubba: it starts here at the gate we entered...
- Bubba:- ... and goes on this way ...
- Bubba: ... until the end of the rocks to sort.
- Bubba: The rocks are all different sizes 
- Bubba: (some can be the same size, it works the same way but it takes less words to describe when they're all different) 
- Bubba: and unordered.
- Bubba: When we're done they'll be ordered from smallest first...
- Bubba: ... to biggest last.
- Bubba: Since we're on this side of the array -
- Bubba: "Sorted" means the smallest rock is the first one on the left.
- Bubba: and every rock to its right is bigger than the rock to its left.
- Bubba: We start sorting here at the beginning.
- Bubba: We put the first rock in our left hand
- Bubba: and the second rock in our right hand.
- Bubba: We then compare the two rocks.
- Bubba: If the right rock is bigger than the left 
- Bubba: Then they are in order so we leave them alone.
- Bubba: If the right rock is smaller than the left
- Bubba: Then we swap them to put them in order.
- Bubba: Bubba call this sorting of right and left "Sort-Two".
- Bubba: Once the two are sorted we move one rock to the right (Bubba call this "Step-One").
- Bubba: The rock now in our left hand was the rock in our left hand at the end of the last Sort-Two.
- Bubba: We pick up the next rock with our right hand and Sort-Two.
- Bubba: Then we Step-One to the right.
- Bubba: This is the basis of Bubba Sort. Sort-Two then Step-One.
- Narrator: Why do you only sort two-rocks at a time?
- Bubba: Bubba only have two hands.
- Bubba: Anyway, We repeat this (Sort-Two, Step-One) until we reach the end and can't Step-One after our last Sort-Two.
- Bubba: We pick up the Magic Chicken Wand (MCW) and move it one to the left so it sits between the last two rocks.
- Bubba: Our unsorted array shrinks by one and the last rock is moved to the sorted array.
- Bubba: If we turn off the Magic Chicken Wand we can see that the array hasn't really shrunk.
- Bubba: The Chicken just uses Magic to split the array into the unsorted on the left.
- Bubba: And the sorted on the right.
- Bubba: Now I turn on the Chicken again and step through the door at the end of the array...
- Bubba: And we end up at the beginning of the unsorted array again (chicken-magic).
- Bubba: We keep doing this over and over again.
- Bubba: Sort-Two and Step One repeatedly until we reach the end...
- Bubba: Move the Magic Chicken Wand one to the left to move the last rock into the sorted
- Bubba: ... and shrink the unsorted.
- Bubba: Until there's only one rock left of the chicken
- Bubba: And then we're done.
 
** Why does this work?
- Narrator: What's the secret to this Bubba-Sort?
- Bubba: No secret. After you sort the first two rocks the rock to your right is smaller than the rock to your left.
- Bubba: Then you take a step to the right.
- Bubba: The left rock is bigger than the rock to its left (because we sorted them)...
- Bubba: And when you sort the rocks in front of you
- Bubba: The rock in your right hand is the biggest of the two in front of you.
- Bubba: This right rock was either originally the left rock, in which case we already know it's bigger than the rock to its left
- Bubba: Or it was already the right rock, in which case it's bigger than the original left rock, which was bigger than the rock to its left.
- Bubba: In either case, the rock on the right is bigger than the left rock and the rock to its left, so it is the biggest rock we've seen so far.
- Bubba: This is true every time we take a step and sort.
- Bubba: Before the Sort-Two the left rock is bigger than every rock to its left.
- Bubba: and after the Sort-Two the right rock is bigger than the left rock and all the rocks to its left.
- Bubba: So when we get to the end of the unsorted bench.
- Bubba: And we do the two-swap.
- Bubba: The rock at the end of the bench is bigger than all the rocks to its left (it's the biggest of the unsorted rocks).
- Bubba: And since every time we move the chicken wand one to the left the rock that it moves past is bigger than all the rocks to its left, all the rocks to the right of the chicken wand are bigger tahn all the rocks to its left.
- Bubba: So before we move the rock at the end of the bench, it's bigger than all the rocks to its left and smaller than all the rocks to its right, so it's in the right place for the final sorted array.
- Bubba: Moving the chicken over puts the last rock at the start of the rocks bigger than it
- Bubba: Moving them in this order means the rocks to the right of the chicken aren't just bigger than those to the left but they're sorted too.
- Bubba: So when we reach the last unsorted rock, everything to the right of the chicken is sorted and the last rock is less than the smallest rock on the sorted side, so the whole array is sorted.
** A Simple Example
- Maybe a simpler example will help clear it up.
- Here's a case with five rocks, all hammajang to start.
- We start by sorting the first two.
- Then sort the next two.
- Then the next two...
