from .partition_levitin import partition_levitin as levitins_partition
from .partition_clrs import partition_clrs as clrs_partition
from .partition_randomized import partition_randomized as randomized_partition
