#+BEGIN_COMMENT
.. title: Insertion Sort
.. slug: insertion-sort
.. date: 2021-11-30 17:15:24 UTC-08:00
.. tags: sorting,algorithms,reduce & conquer,iterative,more of the output
.. category: Sorting
.. link: 
.. description: A look at the Insertion Sort algorithm.
.. type: text
.. has_pseudocode: You betcha.
#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 3
#+PROPERTY: header-args :session ~/.local/share/jupyter/runtime/kernel-a7aef5e7-7fca-483f-80fd-25c7e881cffd-ssh.json
#+BEGIN_SRC python :results none :exports none
%load_ext autoreload
%autoreload 2
#+END_SRC

#+begin_comment
Define small-caps (sc)
https://stackoverflow.com/questions/11576237/mathjax-textsc
#+end_comment

\[
\def\sc#1{\dosc#1\csod} \def\dosc#1#2\csod{{\rm #1{\small #2}}}
\]
* The Algorithm Parts
  This is taken pretty straight from {{% doc %}}HTTAA{{% /doc %}}.

  - **Specification:** This is a {{% lancelot "Sorting Problem" %}}the-sorting-problem{{% /lancelot %}}.
  - **Basic Steps:** Repeatedly insert an item where it belongs.
  - **Measure of Progress:** The number of elements we've inserted so far.
  - **The Loop Invariant:** The inserted elements are in sorted order.
  - **Main Steps:** Take an unselected item and insert it into the correct place in the sorted list.
  - **Make Progress:** We always insert an item.
  - **Maintain the Loop Invariant:**
   + \( \langle \textit{Loop Invariant} \rangle\): Insertion List is sorted.
   + \(\lnot \langle \textit{Exit-Condition} \rangle \): There's more to sort.
   + \(\sc{CodeLoop}\): The item that was chosen was inserted in the place that maintains the loop invariant.
  - **Establish the Loop Invariant:** Pick the first item from the unsorted list giving us a sorted list with one item.
  - **Exit Condition:** We've inserted all the items.
  - **Ending:**
    + \(\langle \textit{Exit-Condition} \rangle\): All elements were inserted.
    + \(\langle \textit{Loop Invariant} \rangle\): All inserted elements are in the right order.
    + \(\rightarrow \langle \textit{Post-Condition} \rangle\): All the elements are in sorted order.
* Sources
 - {{% doc %}}HTTAA{{% /doc %}}
 - {{% doc %}}itdaa{{% /doc %}}

#+begin_export html
<!-- Change the ID once you have some pseudocode
<script>
window.addEventListener('load', function () {
    pseudocode.renderElement(document.getElementById("selectionsort"));
});
</script>
-->
#+end_export
