#+BEGIN_COMMENT
.. title: Comparing Energy Prices
.. slug: comparing-energy-prices
.. date: 2022-07-12 13:13:00 UTC-07:00
.. tags: global warming,unit conversion
.. category: Global Warming
.. link: 
.. description: Using unit-conversion to compare prices for different energy sources.
.. type: text
.. has_math: True
#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 3
#+PROPERTY: header-args :session ~/.local/share/jupyter/runtime/kernel-2f2a654b-7735-4442-957a-10e1f8739df7-ssh.json
#+BEGIN_SRC python :results none :exports none
%load_ext autoreload
%autoreload 2
#+END_SRC
* How Many Megajoules For a Dollar of Gas?
- A gallon of gasoline carries with it \(\approx 1.3E8\) joules of energy.
- You pay \(5 \frac{\text{dollars}}{\text{gallon}}\).
- How many megajoules (\(10^6\) joules) can you get for a dollar?

** Chain-Link Conversion
\begin{align}
\require{cancel}
\left(\frac{1 \cancel{gallon}}{5\textit{ dollars}}\right)\left(\frac{1.3 \times 10^8\textit{ joules}}{1 \cancel{gallon}}\right) &= \left(\frac{1.3 \times 10^8 \cancel{joules}}{5\textit{ dollars}}\right)\left(\frac{1 megajoule}{10^6 \cancel{joule}}\right) \\
&=\frac{1.3\times 10^8 megajoules}{(5 \textit{ dollars})\left(10^6\right)}\\
&= 26 \frac{megajoules}{dollar}
\end{align}

** In Python
#+begin_src python :results output :exports both
from fractions import Fraction

gallons_per_dollar = Fraction(1, 5)
joules_per_gallon = 13 * 10**7
joules_per_dollar = joules_per_gallon * gallons_per_dollar
megajoules_per_joule = Fraction(1, 10**6)
megajoules_per_dollar = joules_per_dollar * megajoules_per_joule
print(f"{megajoules_per_dollar} megajoules/dollar")
#+end_src

#+RESULTS:
: 26 megajoules/dollar

* How Many MegaJoules For a Dollar of Electricity?
- Electricity is $0.05 per kilowatt-hour.
- \(1\text{ watt} = 1 \frac{joule}{second}\)
- \(1\text{ kilowatt-hour} = 1,000\text{ watts} \times 3,600\text{ seconds}\)

** Kilowatt-Hour To Joules
\begin{align}
1 kilowatt-hour &= (1,000\text{ watts})(3,600\text{ seconds})\\
  &= \left(\frac{1,000\text{ joules}}{\cancel{second}}\right)\left(3,600 \cancel{seconds}\right)\\
  &= 36 \times 10^5 \text{ joules}
\end{align}
** A Dollar's Worth Of Megajoules
\begin{align}
\frac{1 \text{ kilowatt-hour}}{0.05\text{ dollars}} &= \left(\frac{3.6 \times \cancel{10^6 joules}}{0.05\text{ dollars}}\right)\left(\frac{1 \text{ megajoule}}{\cancel{10^6 joules}}\right)\\

&= \left(\frac{3.6\ megajoules}{0.05\text{ dollars}}\right)\left(\frac{20}{20}\right) \\
&= 72 \ \frac{megajoules}{dollar}

\end{align}
** Check The Math
#+begin_src python :results output :exports both
kilowatt_hours_per_dollar = 20 # 1/0.05 = 20
megajoules = 3.6
megajoules_per_dollar = kilowatt_hours_per_dollar * megajoules
print(f"{megajoules_per_dollar} megajoules/dollar of electricity")
#+end_src

#+RESULTS:
: 72.0 megajoules/dollar of electricity

* How Many Megajoules For a Dollar Of Natural Gas?
- A standard cubic foot of natural gas has about \(1.1 \times 10^6\) joules of energy.
- You can get about \(5\times 10^5\) BTUs of gas for a dollar.
- There are about 1,030 BTUs in a cubic foot.

\begin{align}
\left(1.1 \times 10^6 \frac{joules}{\cancel{cubic foot}}\right)\left(\frac{1\ \cancel{cubic foot}}{1.03 \times 10^3\ BTU}\right) &= \left(\frac{1.1 \times 10^3\ joules}{1.03\ \cancel{BTU}}\right)\left(\frac{5 \times 10^5\ \cancel{BTU}}{dollar}\right)\\
&= \left(\frac{5.5 \times 10^8\ \cancel{joules}}{1.03\ dollars}\right)\left(\frac{1\ Megajoule}{10^6 \cancel{joules}}\right)\\
&= \left(\frac{5.5 \times 10^2\ Megajoules}{1.03 dollars}\right)\\
&\approx 533.98\ \frac{Megajoules}{dollar}\\
\end{align}

** Check The Math
#+begin_src python :results output :exports both
joules_per_cubic_foot = 1.1E6
cubic_feet_per_btu = 1/1030
btus_per_dollar = 5e5
megajoules_per_joule = 1/(10**6)

joules_per_btu = joules_per_cubic_foot * cubic_feet_per_btu

joules_per_dollar = joules_per_btu * btus_per_dollar
megajoules_per_dollar = joules_per_dollar * megajoules_per_joule
print(f"{megajoules_per_dollar:0.2f} MJ/Dollar")
#+end_src

#+RESULTS:
: 533.98 MJ/Dollar

* Source
 - {{% doc %}}course-global-warming{{% /doc %}}
