#+BEGIN_COMMENT
.. title: Comparing Energy Prices
.. slug: comparing-energy-prices
.. date: 2022-07-12 13:13:00 UTC-07:00
.. tags: global warming,unit conversion
.. category: Global Warming
.. link: 
.. description: Using unit-conversion to compare prices for different energy sources.
.. type: text
.. has_math: True
#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 3
#+PROPERTY: header-args :session ~/.local/share/jupyter/runtime/kernel-b5c6944e-e279-456f-89fb-29fe6af4cf64-ssh.json
#+BEGIN_SRC python :results none :exports none
%load_ext autoreload
%autoreload 2
#+END_SRC
* How Many Megajoules For a Dollar of Gas?
- A gallon of gasoline carries with it \(\approx 1.3E8\) joules of energy.
- You pay \(5 \frac{\text{dollars}}{\text{gallon}}\).
- How many megajoules (\(10^6\) joules) can you get for a dollar?

** Chain-Link Conversion
\begin{align}
\require{cancel}
\left(\frac{1 \cancel{gallon}}{5\textit{ dollars}}\right)\left(\frac{1.3 \times 10^8\textit{ joules}}{1 \cancel{gallon}}\right) &= \left(\frac{1.3 \times 10^8 \cancel{joules}}{5\textit{ dollars}}\right)\left(\frac{1 megajoule}{10^6 \cancel{joule}}\right) \\
&=\frac{1.3\times 10^8 megajoules}{(5 \textit{ dollars})\left(10^6\right)}\\
&= 26 \frac{megajoules}{dollar}
\end{align}

** In Python
#+begin_src python :results output :exports both
from fractions import Fraction

gallons_per_dollar = Fraction(1, 5)
joules_per_gallon = 13 * 10**7
joules_per_dollar = joules_per_gallon * gallons_per_dollar
megajoules_per_joule = Fraction(1, 10**6)
megajoules_per_dollar = joules_per_dollar * megajoules_per_joule
print(f"{megajoules_per_dollar} megajoules/dollar")
#+end_src

#+RESULTS:
: 26 megajoules/dollar

* How Many MegaJoules For a Dollar of Electricity?
- Electricity is $0.05 per kilowatt-hour.
- \(1\text{ watt} = 1 \frac{joule}{second}\)
- \(1\text{ kilowatt-hour} = 1,000\text{ watts} \times 3,600\text{ seconds}\)

** Kilowatt-Hour To Joules
\begin{align}
1 kilowatt-hour &= (1,000\text{ watts})(3,600\text{ seconds})\\
  &= \left(\frac{1,000\text{ joules}}{\cancel{second}}\right)\left(3,600 \cancel{seconds}\right)\\
  &= 36 \times 10^5 \text{ joules}
\end{align}
** A Dollar's Worth Of Megajoules
\begin{align}
\frac{1 \text{ kilowatt-hour}}{0.05\text{ dollars}} &= \left(\frac{3.6 \times \cancel{10^6 joules}}{0.05\text{ dollars}}\right)\left(\frac{1 \text{ megajoule}}{\cancel{10^6 joules}}\right)\\

&= \left(\frac{3.6\ megajoules}{0.05\text{ dollars}}\right)\left(\frac{20}{20}\right) \\
&= 72 \ \frac{megajoules}{dollar}

\end{align}
** Check The Math
#+begin_src python :results output :exports both
kilowatt_hours_per_dollar = 20 # 1/0.05 = 20
megajoules = 3.6
megajoules_per_dollar = kilowatt_hours_per_dollar * megajoules
print(f"{megajoules_per_dollar} megajoules/dollar of electricity")
#+end_src

#+RESULTS:
: 72.0 megajoules/dollar of electricity

* Source
 - {{% doc %}}course-global-warming{{% /doc %}}
