---
title: R-Markdown Syntax Assignment
slug: r-markdown-syntax-assignment
date: 2021-12-10 16:03:47 UTC-08:00
tags: r,assignment,vsfdss,MSDS,data science,
category: Vital Skills For Data Science Specialization
link: 
description: An assignment to work through some R-Markdown syntax.
type: text
fontfamily: ebgaramond
mainfont: Gentium
---

# Bullet-List

- Bull it
    + Et Bull
- Bullitt
    + Bull et
    + Bull, Let

# Numbered List

1. Two
2. Four
3. Three

# Italics

*Some words.*

# Bold Print

**Some words.**

# Two Levels
    
    Level one.
    
## Next Level

    Level Two.

# Some Hidden R Code Output

```{r hidden-code, echo=FALSE}
summary(iris)
```

# A Table

| Alfa   | Bravo | Charley    | Delta  |
|--------|-------|------------|--------|
| Now    | is    | the        | Winter |
| of     | our   | discontent | made   |
| Summer | by    | this       | Son    |

# A Plot
This is from [statology](https://www.statology.org/iris-dataset-r/).

```{r plot-something}
boxplot(Sepal.Length~Species,
        data=iris,
        main='Sepal Length by Species',
        xlab='Species',
        ylab='Sepal Length',
        col='steelblue',
        border='black')
```

# Session Info

```{r session-info}
sessionInfo()
```
