#+BEGIN_COMMENT
.. title: R Markdown Project
.. slug: r-markdown-project
.. date: 2021-12-09 16:06:39 UTC-08:00
.. tags: r,assignment,vsfdss,MSDS,data science
.. category: Vital Skills For Data Science Specialization
.. link: 
.. description: 
.. type: text

#+END_COMMENT
* Reproducibility
** Knit the Template

Knit the template Rmd to both HTML and PDF. "The Template" just means open a new file in R Studio.

** Use R Markdown to Create a Document

Use R Markdown to create your own document containing [9/9] :

  - [X]  a bulleted list with sub-bullets under at least one item 
  - [X]  a numbered list 
  - [X]  some words italicized 
  - [X]  some words in bold print 
  - [X]  two levels of headers
  - [X]  the results of some R code without showing the code 
  - [X]  a table of text at least 3 columns wide and 3 rows long 
  - [X]  a plot (show the code that generates the plot) 
  - [X]  your session info (as output from R) 

Be sure to put text before and after each code chunk that you include. Your document should be knitted into both a .html and a .pdf.  Post any issues in the discussion board and help your colleagues that are having trouble there.
* Steps In the Data Science Process Through Data Cleaning
To access the files for the project in this module, go to https://catalog.data.gov/dataset  and find the dataset titled [[https://catalog.data.gov/dataset/nypd-shooting-incident-data-historic][NYPD Shooting Incident Data (Historic)]].  Right click on the CSV button and copy the link address
(https://data.cityofnewyork.us/api/views/833y-fsy8/rows.csv?accessType=DOWNLOAD). You will then put this link address into your Rmd when you are reading in the dataset.  This project will be built up over the week and will be peer-reviewed as part of your grade at the end of the week.

* Project Step 1: Start an Rmd Document

Start an Rmd document that describes and imports the shooting project dataset in a reproducible manner.

* Project Step 2: Tidy and Transform Your Data

Add to your Rmd document a summary of the data and clean up your dataset by changing appropriate variables to factor and date types and getting rid of any columns not needed.  Show the summary of your data to be sure there is no missing data. If there is missing data, describe how you plan to handle it.
* Project Step 3: Add Visualizations and Analysis

Add at least two different visualizations & some analysis to your Rmd.  Does this raise additional questions that you should investigate?  

* Project Step 4: Add Bias Identification

Write the conclusion to your project report and include any possible sources of bias.  Be sure to identify what your personal bias might be and how you have mitigated that.
